name: AstrbotAdapter
version: '${project.version}'
main: io.github.railgun19457.astrbotadapter.AstrbotAdapter
api-version: '1.20'
api: '1.20'
description: Minecraft server plugin for AstrBot integration
author: railgun19457
website: https://github.com/railgun19457/AstrBotAdapter

commands:
  astrbot:
    description: AstrBot plugin commands
    usage: /<command> [reload|status|help]
    permission: astrbot.admin
    aliases: [ab]

permissions:
  astrbot.admin:
    description: Allows access to AstrBot admin commands
    default: op
